### ISSUE TITLE
Module not found: Can't resolve 'markmap-common'

### ISSUE THREAD

**Issue by raven-rwho** [markmap/markmap#139]
Hi,

I've tried to build a component based on Markmap (thanks fot it - it is a brilliant vizulisation!) inside of a next project

I basically copy pasted this code
https://stackblitz.com/edit/markmap?file=index.tsx,markmap-hooks.tsx,node_modules%2F%40types%2Freact%2Findex.d.ts
after installing markmap-lib and markmap-view via yarn.

Unfrotunately the project can't be build because of

`error - ./node_modules/markmap-view/dist/index.esm.js:2:0
Module not found: Can't resolve 'markmap-common'

Import trace for requested module:
./pages/markdown.tsx

https://nextjs.org/docs/messages/module-not-found
error - Error: Cannot find module 'markmap-common'
Require stack:
- /data-fetch-app/node_modules/markmap-lib/dist/index.js
- /data-fetch-app/.next/server/pages/markdown.js
- /data-fetch-app/node_modules/next/dist/server/require.js
- /data-fetch-app/node_modules/next/dist/server/next-server.js
- /data-fetch-app/node_modules/next/dist/server/next.js
- /data-fetch-app/node_modules/next/dist/server/lib/start-server.js
- /data-fetch-app/node_modules/next/dist/cli/next-dev.js
- /data-fetch-app/node_modules/next/dist/lib/commands.js
- /data-fetch-app/node_modules/next/dist/bin/next
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at mod._resolveFilename (/data-fetch-app/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at mod._resolveFilename (/data-fetch-app/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at mod._resolveFilename (/data-fetch-app/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/data-fetch-app/node_modules/markmap-lib/dist/index.js:5:21)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10) {
  code: 'MODULE_NOT_FOUND',`

Could you help me with it?

Best!

**Comment by raven-rwho** [comment]
Found the issue and it has nothing to do with the lib
