### ISSUE TITLE
[BUG] markmap-cli failing in node v16.20.1

### ISSUE THREAD

**Issue by Zeioth** [markmap/markmap#197]
**Describe the bug**

It used to work fine, but it doesn't now:

```sh
markmap -o /tmp/markmap.html /home/zeioth/myfile.md                                                                                                     

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[AggregateError: All promises were rejected] {
  [errors]: [
    ReferenceError: fetch is not defined
        at /home/zeioth/.config/yarn/global/node_modules/markmap-common/dist/index.js:31:19
        at Array.map (<anonymous>)
        at UrlBuilder.getFastestProvider (/home/zeioth/.config/yarn/global/node_modules/markmap-common/dist/index.js:30:55)
        at UrlBuilder.findFastestProvider (/home/zeioth/.config/yarn/global/node_modules/markmap-common/dist/index.js:40:32)
        at createMarkmap (file:///home/zeioth/.config/yarn/global/node_modules/markmap-cli/dist/index.js:321:34)
        at Command.<anonymous> (file:///home/zeioth/.config/yarn/global/node_modules/markmap-cli/dist/index.js:367:13),
    ReferenceError: fetch is not defined
        at /home/zeioth/.config/yarn/global/node_modules/markmap-common/dist/index.js:31:19
        at Array.map (<anonymous>)
        at UrlBuilder.getFastestProvider (/home/zeioth/.config/yarn/global/node_modules/markmap-common/dist/index.js:30:55)
        at UrlBuilder.findFastestProvider (/home/zeioth/.config/yarn/global/node_modules/markmap-common/dist/index.js:40:32)
        at createMarkmap (file:///home/zeioth/.config/yarn/global/node_modules/markmap-cli/dist/index.js:321:34)
        at Command.<anonymous> (file:///home/zeioth/.config/yarn/global/node_modules/markmap-cli/dist/index.js:367:13)
  ]
}
```

**To Reproduce**

on `node v16.20.1` run `markmap -o /tmp/markmap.html ~/myfile.md`

**Expected behavior**

A html file is generated in /tmp/markmap.html

**Actual behavior**

An error is displayed and the file is not created. 

![screenshot_2023-07-25_19-39-12_544826531](https://github.com/markmap/markmap/assets/3357792/6c3b04c5-96b5-4847-91b7-df0d4267f185)

**Environment:**

- OS: arch
- Browser: Firefox 115.0.2
- Browser Version: [e.g. 22]

**Additional context**

The -w flag seems to at least open the html in the browser though.

my markmap version is 0.15.2 but it also hapen with 0.14, so the cause is probably  a new node version.

**Comment by gera2ld** [comment]
Right, `fetch` is only available in Node.js >= 18. I'll fix it by ignoring the errors for Node 16.

**Comment by Zeioth** [comment]
I can confirm that fixed it. Thank you Gerald.
