### ISSUE TITLE
[BUG] markmap --watch --offline not working

### ISSUE THREAD

**Issue by MarcoBuess** [markmap/markmap#234]
- [x] I have searched for existing issues that already reported this problem and found none
- [ ] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Describe the bug**
Running `markmap --offline --watch <any>.md` yields an error.

**To Reproduce**
Run above command in an offline scenario.

**Expected behavior**
Correctly renders and updates.

**Actual behavior**
```console
C:\Users\****\AppData\Roaming\npm\node_modules\markmap-cli\node_modules\markmap-common\dist\index.js:40
        timer = setTimeout(reject, timeout, new Error("Timed out"));
                                            ^

Error: Timed out
    at C:\Users\****\AppData\Roaming\npm\node_modules\markmap-cli\node_modules\markmap-common\dist\index.js:40:45
    at new Promise (<anonymous>)
    at UrlBuilder.getFastestProvider (C:\Users\****\AppData\Roaming\npm\node_modules\markmap-cli\node_modules\markmap-common\dist\index.js:30:20)        
    at fetchAssets (file:///C:/Users/****/AppData/Roaming/npm/node_modules/markmap-cli/dist/index.js:384:48)
    at Command.<anonymous> (file:///C:/Users/****/AppData/Roaming/npm/node_modules/markmap-cli/dist/index.js:506:13)
    at Command.listener [as _actionHandler] (C:\Users\****\AppData\Roaming\npm\node_modules\markmap-cli\node_modules\commander\lib\command.js:494:17)    
    at C:\Users\****\AppData\Roaming\npm\node_modules\markmap-cli\node_modules\commander\lib\command.js:1296:65
    at Command._chainOrCall (C:\Users\****\AppData\Roaming\npm\node_modules\markmap-cli\node_modules\commander\lib\command.js:1193:12)
    at Command._parseCommand (C:\Users\****\AppData\Roaming\npm\node_modules\markmap-cli\node_modules\commander\lib\command.js:1296:27)
    at Command.parse (C:\Users\****\AppData\Roaming\npm\node_modules\markmap-cli\node_modules\commander\lib\command.js:910:10)

Node.js v18.16.0
```

**Environment:**
Caption: Microsoft Windows 10 Enterprise
Version: 10.0.19045
OSArchitecture: 64-bit

**Comment by gera2ld** [comment]
It looks like a network issue. The offline mode works by downloading all assets in advance.
Can you access the assets directly?

https://cdn.jsdelivr.net/npm/markmap-view@0.16.0/dist/browser/index.min.js

**Comment by MarcoBuess** [comment]
Looks like so. But does that even make sense? Its literally like an offline mode that doesn't work offline. It also doesn't look like it works offline even with an active connection. It doesn't seem like it caches the assets locally to have it really work offline?

**Comment by gera2ld** [comment]
The offline mode works by downloading the assets in advance during installation. The installation still requires a network. Now the issue is that installation failed due to a network problem.

BTW does any CDN that serves npm package files work for you? I can tell that both jsdelivr and unpkg do not.

**Comment by MarcoBuess** [comment]
So I'm behind a corp. firewall. It is usually fine with `npm` but I can't tell for anything beyond that. So what you're saying is, if e.g. I have a non restricted connection the `-offline` switch would download the assets and it should work from then on, or I have to do a whole reinstallation of `markmap` with a non restricted connection?

**Comment by MarcoBuess** [comment]
@gera2ld So I tried both. It looks like it tries to download the assets again everytime your run it, no matter if it ran sucessfully before. Outside the corp. network, I can run with `-offline` just fine. I also reinstalled `v0.16.1` outside the corp. network. As soon as I reconnect to the corp. network it stops working.

**Comment by gera2ld** [comment]
Seems something is wrong with paths after installation. Let me fix it.

**Comment by MarcoBuess** [comment]
@gera2ld Can confirm it's working now. Thanks. 👍

**Comment by gera2ld** [comment]
`--offline` means the generated HTML file can be loaded offline, i.e. all static assets are inlined.
If all the assets are downloaded successfully on installation, you don't need a network to use it, no matter if `--watch` is set.
An exception is that Katex requires font files that must be downloaded from the CDN.
