### ISSUE TITLE
[BUG] Update Markmap-lib 0.14 to 0.17 for an Obsidian extension

### ISSUE THREAD

**Issue by eldertek** [markmap/markmap#246]
- [X] I have searched for existing issues that already reported this problem and found one but can't apply the solution
**Describe the bug**
Hello, I am trying to update markmap in my obsidian extension.

**To Reproduce**
Update markmap-lib to version 0.15-0.17 in the plugin's package.json.
Build my plugin using Rollup.
Attempt to activate the plugin in Obsidian.
Observe the errors related to highlight.js.

** Error ** 
plugin:obsidian-enhancing-mindmap:39913 Language definition for '1c' could not be registered.
plugin:obsidian-enhancing-mindmap:39913 TypeError: languageDefinition is not a function
    at Object.registerLanguage (plugin:obsidian-enha…ng-mindmap:41338:14)
    at anonymous (plugin:obsidian-enha…ing-mindmap:44218:6)
    at e.<anonymous> (app.js:1:2243790)
    at app.js:1:237056
    at Object.next (app.js:1:237161)
    at a (app.js:1:235879)

**Comment by eldertek** [comment]
Code is here : https://github.com/eldertek/obsidian-enhancing-mindmap

**Comment by eldertek** [comment]
Fixed by just disabling hljs
